export const ALBUM_BACKGROUND_ORIGIN =
  'https://karuta-bot.s3.us-east-2.amazonaws.com/images/backgrounds'

const ROWS: Array<[string, string]> = [
  ['default', 'Default'],
  ['abstractdragons', 'Abstract Dragons'],
  ['adventmidgar', 'Advent Midgar'],
  ['aincard', 'Aincrad'],
  ['akinapass', 'Akina Pass'],
  ['altusparis', 'Altus Paris'],
  ['anothergalaxy', 'Another Galaxy'],
  ['autumnleaves', 'Autumn Leaves'],
  ['beigelinen', 'Beige Linen'],
  ['betweenthetrees', 'Between the Trees'],
  ['blackgold', 'Black Gold'],
  ['blueglitter', 'Blue Glitter'],
  ['blurbow', 'Blurbow'],
  ['boarhatbar', 'Boar Hat Bar'],
  ['boneeaterswell', "Bone-Eater's Well"],
  ['brickinthewall', 'Brick in the Wall'],
  ['bridgetopiltover', 'Bridge to Piltover'],
  ['brushthesky', 'Brush the Sky'],
  ['budokan', 'Budokan'],
  ['cherryblossombranch', 'Cherry Blossom Branch'],
  ['cityofprogress', 'City of Progress'],
  ['coffeebeans', 'Coffee Beans'],
  ['corkboard', 'Corkboard'],
  ['damvant', 'Damvant'],
  ['darkplaster', 'Dark Plaster'],
  ['dirtybuster', 'Dirty Buster'],
  ['dirtystucco', 'Dirty Stucco'],
  ['draculascastle', "Dracula's Castle"],
  ['fieldofblades', 'Field of Blades'],
  ['finestucco', 'Fine Stucco'],
  ['flowercapital', 'Flower Capital'],
  ['fromthealley', 'From the Alley'],
  ['frozenlake', 'Frozen Lake'],
  ['fujikasanewisterias', 'Fujikasane Wisterias'],
  ['goldfoil', 'Gold Foil'],
  ['goldglitter', 'Gold Glitter'],
  ['gracefieldhouse', 'Grace Field House'],
  ['grantesoro', 'Gran Tesoro'],
  ['greatwarsky', 'Great War Sky'],
  ['greendolphinstreetprison', 'Green Dolphin Street Prison'],
  ['greenfuzz', 'Green Fuzz'],
  ['greenglitter', 'Green Glitter'],
  ['grime', 'Grime'],
  ['groundgamma', 'Ground Gamma'],
  ['grunge', 'Grunge'],
  ['hackingtothegate', 'Hacking to the Gate'],
  ['hazefield', 'Hazefield'],
  ['hextechgate', 'Hextech Gate'],
  ['higurashishrine', 'Higurashi Shrine'],
  ['holygrailwar', 'Holy Grail War'],
  ['hyakkaouprivateacademy', 'Hyakkaou Private Academy'],
  ['infinitetatami', 'Infinite Tatami'],
  ['infinitevoid', 'Infinite Void'],
  ['jinxsbombpit', "Jinx's Bomb Pit"],
  ['justred', 'Just Red'],
  ['justyellow', 'Just Yellow'],
  ['kamadocherryblossoms', 'Kamado Cherry Blossoms'],
  ['kingdomofelkia', 'Kingdom of Elkia'],
  ['kingdomofnifl', 'Kingdom of Nifl'],
  ['kokirishouse', "Kokiri's House"],
  ['lanternfestival', 'Lantern Festival'],
  ['leidenleidenschaftlich', 'Leiden, Leidenschaftlich'],
  ['liyueharbor', 'Liyue Harbor'],
  ['marinsroom', "Marin's Room"],
  ['maroongalaxy', 'Maroon Galaxy'],
  ['meruemspalace', "Meruem's Palace"],
  ['metalfabricator', 'Metal Fabricator'],
  ['metrolookout', 'Metro Lookout'],
  ['midnightchannel', 'Midnight Channel'],
  ['milkyway', 'Milky Way'],
  ['mondstat', 'Mondstadt'],
  ['moonandstars', 'Moon and Stars'],
  ['moonovermorisawas', "Moon Over Morisawa's"],
  ['morioh', 'Morioh'],
  ['morisawashouse', "Morisawa's House"],
  ['musicpreproom', 'Music Prep Room'],
  ['musicalscore', 'Musical Score'],
  ['nanachishouse', "Nanachi's House"],
  ['neighborslawn', "Neighbor's Lawn"],
  ['nerimaward', 'Nerima Ward'],
  ['onetruegodboard', 'One True God Board'],
  ['orangeburst', 'Orange Burst'],
  ['ouranclocktower', 'Ouran Clock Tower'],
  ['overthecity', 'Over the City'],
  ['pacificleather', 'Pacific Leather'],
  ['pegasusduelarena', 'Pegasus Duel Arena'],
  ['pinkglitter', 'Pink Glitter'],
  ['powerup', 'Power Up'],
  ['prisonlineup', 'Prison Lineup'],
  ['purpleglitter', 'Purple Glitter'],
  ['rainbowsakura', 'Rainbow Sakura'],
  ['sacredtorii', 'Sacred Torii'],
  ['saespalace', "Sae's Palace"],
  ['sagirimountainnight', 'Sagiri Mountain Night'],
  ['shintopass', 'Shinto Pass'],
  ['silverglitter', 'Silver Glitter'],
  ['simplypeach', 'Simply Peach'],
  ['skulldome', 'Skull Dome'],
  ['skynet', 'Sky Net'],
  ['speckledblue', 'Speckled Blue'],
  ['springgreenery', 'Spring Greenery'],
  ['stainedmetal', 'Stained Metal'],
  ['stoneearth', 'Stone Earth'],
  ['sunsetbridge', 'Sunset Bridge'],
  ['synthwave', 'Synthwave'],
  ['theabyss', 'The Abyss'],
  ['thehopediamond', 'The Hope Diamond'],
  ['thelastdrop', 'The Last Drop'],
  ['theredroom', 'The Red Room'],
  ['timelapse', 'Time Lapse'],
  ['tokyofuture', 'Tokyo Future'],
  ['tokyometropolitangymnasium', 'Tokyo Metropolitan Gymnasium'],
  ['traintoheaven', 'Train to Heaven'],
  ['treehouseoffun', 'Treehouse of Fun'],
  ['uahighschool', 'U.A. High School'],
  ['upthestreet', 'Up the Street'],
  ['uponastar', 'Upon a Star'],
  ['usdollar', 'US Dollar'],
  ['villagehilltop', 'Village Hilltop'],
  ['wallmaria', 'Wall Maria'],
  ['westinmarble', 'Westin Marble'],
  ['whitecloverwoods', 'White Clover Woods'],
  ['whitebark', 'Whitebark'],
  ['wonderland', 'Wonderland'],
  ['wrightanythingagency', 'Wright Anything Agency'],
  ['x791guildhouse', 'X791 Guild House'],
  ['yamazakurarecord', 'Yamazakura Record']
]

export const ALBUM_BACKGROUND_NAMES: Record<string, string> = Object.fromEntries(ROWS)

export function albumBackgroundName(key: string): string {
  return ALBUM_BACKGROUND_NAMES[key] ?? key
}

export function albumBackgroundUrl(key: string): string {
  return `${ALBUM_BACKGROUND_ORIGIN}/${key}.jpg`
}
